USE master
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT AUTHORITY\SYSTEM]
GO

CREATE AVAILABILITY GROUP [SQLAOAG]
WITH 
(
   AUTOMATED_BACKUP_PREFERENCE = PRIMARY,
   DB_FAILOVER = ON,
   DTC_SUPPORT = NONE
)
FOR DATABASE [Northwind]
REPLICA ON 
N'SQLAO1' WITH 
(
   ENDPOINT_URL = N'TCP://SQLAO1:5022', 
   FAILOVER_MODE = AUTOMATIC,
   SEEDING_MODE = AUTOMATIC,
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT
),
   
N'SQLAO2' WITH 
(
   ENDPOINT_URL = N'TCP://SQLAO2:5022',
   FAILOVER_MODE = AUTOMATIC,
   SEEDING_MODE = AUTOMATIC, 
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT
)
GO