CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'y0ur$ecUr3PAssw0rd';  
GO

CREATE CERTIFICATE SQLAO2_cert
WITH SUBJECT = 'SQLAO2_cert_Private - Node 2',
START_DATE = '20180201'
GO

-- Backup the public key of the certificate to the filesystem
BACKUP CERTIFICATE SQLAO2_cert
TO FILE = 'c:\TempDSCAssets\SQLAO2_cert.cert'
GO

CREATE ENDPOINT Endpoint_AvailabilityGroup 
STATE = STARTED  
AS TCP
(
   LISTENER_PORT = 5022, LISTENER_IP = ALL
)  
   FOR DATABASE_MIRRORING 
(
   AUTHENTICATION = CERTIFICATE SQLAO2_cert, 
   ENCRYPTION = REQUIRED ALGORITHM AES,
   ROLE = ALL 
);  
GO